// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  manualeSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduzione",
    },

    {
      type: "category",
      label: "Gestione e analisi",
      items: [{ type: "autogenerated", dirName: "Gestione e analisi" }],
    },
 {
      type: "category",
      label: "Admin",
      items: [{ type: "autogenerated", dirName: "Admin" }],
    },
    {
      type: "category",
      label: "Knowoledge base",
      items: [{ type: "autogenerated", dirName: "Knowoledge base" }],
    },
  
  ],
};

module.exports = sidebars;
