// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  manualeSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduzione",
    },
    {
      type: "category",
      label: "Funzionalità",
      items: [{ type: "autogenerated", dirName: "funzionalita" }],
    },
  ],
};

module.exports = sidebars;
