// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  manualeSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduzione",
    },

    {
      type: "category",
      label: "Gestione e analisi",
      items: [{ type: "autogenerated", dirName: "Gestione e analisi" }],
    },

    {
      type: "category",
      label: "Governance",
      items: [{ type: "autogenerated", dirName: "governance" }],
    },
  ],
};

module.exports = sidebars;
